# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8ecaf44fe37058ce396c6db29c7b604ab4c4ab93a6dc61411193d09d034a7233ec8558d93f659003df1dea58bc273c3016131ea7ab8313d546f507e2e133238

test:
  secret_key_base: 403edae1055dd200d97774966468714bdcbf585c400b861a1946be14cea4adf770b41d7d3b93751f52424938467c8f66b798b5507152bb4322ae948b3ebffd0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
